### ISSUE TITLE
Failed to save memory card to <Location>

### ISSUE THREAD

**Issue by toniosj** [libretro/swanstation#10]
When I use a NAS, Swanstation shows an error saving to memory card.

I have the same problem with Duckstation & Swanstation on Recalbox and Batocera. So, I think that it's a core problem.

https://gitlab.com/recalbox/recalbox/-/issues/1654

https://github.com/batocera-linux/batocera.linux/issues/5366

**Comment by DarthMew** [comment]
Does this problem occur when setting the memory card type to "Libretro"?

**Comment by toniosj** [comment]
> 

It works with card type "Libretro" !!!

**Comment by DarthMew** [comment]
That's because the "Libretro" format bypasses the whole pathing bit Duckstation likes to do with memory cards (which explains why it's a problem with both standalone as well as both Swanstation and Duckstation cores).
And seeing as this isn't the first time it causes issues with people's memory cards, I'm more and more tempted to just simply remove the memory card selection for Memcard 1 and just default it to Libretro .srm (Memcard 2 would still be using Duckstation's formats, as Swanstation doesn't use Libretro .srm for slot 2 anyway).

**Comment by toniosj** [comment]
> 

I think that it would be a good solution. Thanks!!!

**Comment by DarthMew** [comment]
I've given it a more detailed explanation with https://github.com/libretro/swanstation/commit/9d95c03f5affac2d940df37f845e4e847d535199 on what memcard types are and aren't supported for Swanstation.
