### ISSUE TITLE
Backport MDEC fix?

### ISSUE THREAD

**Issue by vanfanel** [libretro/swanstation#124]
Hi there @DarthMew 

There is a long time issue with MDEC decompression that causes strange transparent rectangles in Resident Evil. 
Here is the same problem in the FPGA MDEC implementation, which also comes from the same code base:
https://github.com/MiSTer-devel/PSX_MiSTer/issues/260

Now, there is a commit that fixes that issue:

https://github.com/stenzek/duckstation/commit/6d6659c85ea83b33b21d573083f6872fa61b0896

Could it be backported to Swanstation?

**Comment by DarthMew** [comment]
Implemented via https://github.com/libretro/swanstation/commit/b9bbf8725436f2ef2b8ef2c835d5b0ce3d60158b

Be sure to check that "Use Old MDEC Routines" is turned off, as since https://github.com/libretro/swanstation/commit/834a6f12413dfa7c58675ad54cad522cd0438663 it is turned on by default for compatibility reasons.

**Comment by vanfanel** [comment]
Nice!

What compatibility reasons are there to not use the new MDEC routines? Could you point me to a game that has problems with them?

**Comment by vanfanel** [comment]
Ah, I understand now.. old MDEC routines are meant for texture substitution, etc.

Thanks!
