### ISSUE TITLE
[RPi4/RPi3] Logitech F710 doesn't work on Dualshock mode with swanstation.

### ISSUE THREAD

**Issue by ghost** [libretro/swanstation#25]
System: Raspbery Pi4 and Raspberry Pi3
Operation System : Lakka v2.4 (64 bit), Batocera v34 (64 bit)
Gamepad : Logitech F710 wireless.
Test game : Ape Escape (USA)
Lakka lr-swanstation core version :commit 0e27584

Logitech controller doesn't work correct on Dualshock mode with the above systems. I have enable the mode from RetroArch menu. Specifically, right stick and vibration doesn't work at all. Game working fine with the lr-pcsx-rearmed emulator on the same systems. 
 
Thanks.

**Comment by DarthMew** [comment]
So you have set the controller type to "DualShock", am I correct?
Also, are you changing the controller type after init by any change, because it seems the version of SwanStation you're using is missing https://github.com/libretro/swanstation/commit/c706125769c5f5137bd057bcf4f4c2585f8798a6

And if that doesn't help, it might be that the DualShock analog needs to forced, which can be done by enabling "Controller 1 Force Analog Mode on Reset" for the specific game you want to have it apply to.

**Comment by ghost** [comment]
> 

Yes i set controller to Dualshock from RA menu, it was the only change i did.

After i enable "Controller 1 Force Analog Mode on Reset" l, controller is working fine now. Thank you !
