### ISSUE TITLE
Transformers beast wars transmetals for psx freeze before title screen

### ISSUE THREAD

**Issue by Mrmath7** [libretro/swanstation#48]
Fix up Transformers beast wars transmetals for psx title screen, because it freezes after opening scene.

**Comment by MistyDreams** [comment]
its broke even worse now since the lastest  commits 6b13636a60bd5494584d6a81d1b82211fd67d185 sounds all choppy now and the game still doesnt work. Seems it works ( sound and game) if in fulls screen but sound is choppy in windowed mode  now is slow and image also is init centered,  its unusable the in this mode game does start though if you wait long enough since its so slow.

**Comment by LibretroAdmin** [comment]
It was just a backport, anyway we can revert it for now. Methinks this regression you have in this game is part of some fundamental issue with this emulator regardless.

Have you tried PCSX ReARMed or Beetle PSX perhaps with this game? perhaps they fare better.

**Comment by Mrmath7** [comment]
> It was just a backport, anyway we can revert it for now. Methinks this regression you have in this game is part of some fundamental issue with this emulator regardless.
> 
> Have you tried PCSX ReARMed or Beetle PSX perhaps with this game? perhaps they fare better.

I know, but it Locks up during loading screen. (CD timing issue) for pcsx rearmed.

**Comment by MistyDreams** [comment]
> It was just a backport, anyway we can revert it for now. Methinks this regression you have in this game is part of some fundamental issue with this emulator regardless.

I tried other cores and the window is running slow for them as well(sometimes other times its ok). Ill wait for a new mesa update because gl output is foo bared on RA but the game displays fine if running from the command line. Only vulkan and glcore works properly for me. I doubt this is completely RA because even older versions that did work arent now with gl and i cant be bother compiling newer mesa drivers.

**Comment by DarthMew** [comment]
The game should now work with https://github.com/libretro/swanstation/commit/cba00efc2568d5b7a5da5883de1997ecdd0dcec3
