### ISSUE TITLE
Use "cache_directory" for Vulkan shader caches instead of "system_directory"

### ISSUE THREAD

**Issue by taki-sahli** [libretro/swanstation#86]
Hello,
`SwanStation` uses `system` directory for it's Vulkan shared caches, this is incorrect, `system` contains BIOS and firmwares to be used by emulators.
And the name of the cache are lower cases `swanstation`, should be `SwanStation` like it's configuration name.

I use this configuration in `RetroArch` to override core's configuration:
```ini
system_directory = "/storage/emulated/0/Firmwares/Sony - PlayStation"
cache_directory = "/storage/emulated/0/.data/user/cache/retroarch"
rgui_config_directory = "/storage/emulated/0/.data/user/roaming/retroarch/config"
savefile_directory = "/storage/emulated/0/.data/user/share/swanstation/saves"
savestate_directory = "/storage/emulated/0/.data/user/share/swanstation/states"
```

https://github.com/libretro/swanstation/blob/afb6bc73c7ce522190b19ec3e3c8a14eb264bdeb/src/libretro/libretro_host_interface.cpp#L401

![image](https://github.com/libretro/swanstation/assets/25118467/38d84d2a-4e80-4878-b8fb-2fefc8bf1152)
![image](https://github.com/libretro/swanstation/assets/25118467/8f0dbe5d-32a2-4b92-8e52-8f4f6dab1680)

Best Regards,

**Comment by DarthMew** [comment]
It's not incorrect for the following reasons:
- Not every RetroArch setup has an already defined cache directory, so relying on it might create undesirable situations for those setups that have this not configured.
- As suggested by the description given, the cache directory is for archived content to be temporarily extracted to, hinting it probably will be wiped when RetroArch gets shut down and means the shader cache would have to be rebuild every time you'd launch SwanStation after closing the frontend.
- SwanStation isn't the only core to use the system directory to store shader caches (Mupen64Plus-Next does this as well), and in general it is fine to use the system directory to store these, as this directory stores files related to the emulator to function and is typically excluded from any sort of file syncing services (the shader cache used to be located in the saves directory before I moved it to the system directory).

On the subject of capitalization, Changing it would be extremely pointless because A.) it would leave people with yet another orphaned cache directory, and B.) wouldn't even matter on platforms that ignore capitalization (E.G. Windows) 
On top of that, many cores simply don't bother to use it when creating folders, and it's a matter of preference of the people working on them if this happens or not.

So no, it's not going to change, and I'm closing this as not planned.
